version: '3'

services:
  beat:
        image: docker.elastic.co/apm/apm-server:6.6.1
        ports:
            - "8200:8200"
#            - "8201:8200"
        environment:
            - apm-server.host=0.0.0.0
        volumes:
            - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
        depends_on:
          - elasticsearch
          - elasticsearch2
          - kibana
        healthcheck:
          test: ['CMD', 'curl', '-f', 'http://localhost:8200']
          interval: 10s
          timeout: 5s
          retries: 3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/Arul/Docker/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/Arul/Docker/esdata2:/usr/share/elasticsearch/data
    ports:
      - "9200"
      - "9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
